# Default configuration (applies if no profile is active)
server:
  port: 8080

# application.yml
anonymiser:
  affine:
    a: 5  # Choose an integer that's coprime with n
    b: 7  # Any integer for translation
    n: 1000  # Modulus, typically a large prime number
    
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/mydb
#     username: user
#     password: pass

# # Profile-specific configurations
# ---
# spring:
#   profiles: dev
# server:
#   port: 8081
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/devdb

# ---
# spring:
#   profiles: prod
# server:
#   port: 8082
# spring:
#   datasource:
#     url: jdbc:mysql://prod-host:3306/proddb
#     username: produser
#     password: prodpass